services:
  _defaults:
    autowire: true
  os2display.slidesInSlidesCron:
    class: Reload\Os2DisplaySlideTools\Service\SlidesInSlideDataCron
    arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher', '@logger', false]
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron }
