services:
  _defaults:
    autowire: true
  reload.ddbos2display:
    class: Reload\Os2DisplaySlideTools\Service\SlidesInSlideDataCron
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron }
